### ISSUE TITLE
doc update: URL 404

### ISSUE THREAD

**Issue by gordielachance** [tchapi/timeuh-machine#10]
https://github.com/tchapi/timeuh-machine/blob/224a4480672e6fd2dbe2997b958194eb05bc9097/templates/about.html.twig#L11

Cette page (http://player.radiomeuh.com/playlist) n'est plus active (erreur 404).
Si tu connais un endpoint existant pour récupérer leurs dix derniers titres, je suis preneur.

**Comment by tchapi** [comment]
L'endpoint est disponible une fois authentifié: https://www.radiomeuh.com/radio/historique

Mis à jour avec https://github.com/tchapi/timeuh-machine/commit/17a515177375c62eaa5c5193457384af71d05b1f
